# Generated by Django 3.2.12 on 2023-01-27 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='s_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.sclass'),
        ),
    ]
